# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgen', '0002_randompage_html_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randompage',
            name='html_string',
            field=models.TextField(default=''),
        ),
    ]
